spring:
  application:
    name: FakeCommerce
  datasource:
    url: jdbc:mysql://localhost:3306/fakecommerce
    username: root
    password: newpassword
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  flyway:
    enabled: true
    locations: classpath:db/migrations
  devtools:
    restart:
      enabled: true
      poll-interval: 2000
      quiet-period: 1000

